### ISSUE TITLE
Anormal hoogle result differences between LTS and Nightly

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stackage-server#183] opened 2016-06-16 21:30 UTC
There is anormal hoogle result differences between LTS and Nightly

👉 Is `base` documentation missing in nightly hoogle DB ?
## Query

```
:: Ord b => b -> b -> b
```
## LTS results

https://www.stackage.org/lts-6.3/hoogle?q=%3A%3A+Ord+b+%3D%3E+b+-%3E+b+-%3E+b

top 3 results:

```
max :: Ord a => a -> a -> a
base    Prelude
No documentation available.

min :: Ord a => a -> a -> a
base    Prelude
No documentation available.

max :: Ord a => a -> a -> a
base    Data.Ord
```
## Nightly results

https://www.stackage.org/nightly/hoogle?q=%3A%3A+Ord+b+%3D%3E+b+-%3E+b+-%3E+b

top 3 results:

```
(≤) :: Ord α => α -> α -> Bool
base-unicode-symbols    Data.Ord.Unicode
(≤) = (<=)

U+2264, LESS-THAN OR EQUAL TO

(≥) :: Ord α => α -> α -> Bool
base-unicode-symbols    Data.Ord.Unicode
(≥) = (>=)

U+2265, GREATER-THAN OR EQUAL TO

(≮) :: Ord α => α -> α -> Bool
base-unicode-symbols    Data.Ord.Unicode
(≮) = (>=)

U+226E, NOT LESS-THAN
```

**Comment by chrisdone** [comment] 2016-07-15 17:05
Think this is the same as #186.

**Comment by chreekat** [comment] 2024-05-16 08:08
Can't reproduce anymore. Closing.

**Closed by chreekat** 2024-05-16 08:08 UTC
Labels: type: bug
